# Site settings
title: Portfolio of David Abling - Graphic, Web & Visual Designer, Wordpress Hacker, Freelancer at Zion Eye Media
email: d_abling@hotmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
twitter_username: jekyllrb
github_username:  jekyll
baseurl: "/portfolio"

# Build settings
markdown: kramdown
permalink: pretty
